name: Deploy to production

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: yarn install
    - run: yarn deploy 
      env:
        AIRTABLE_AUTHORIZATION: ${{ secrets.AIRTABLE_AUTHORIZATION }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

