name: Deploy to production

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch:
  schedule:
    - cron: '57 10 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install
    - run: yarn deploydev # deploy or deploydev
      env:
        AIRTABLE_AUTHORIZATION: ${{ secrets.AIRTABLE_AUTHORIZATION }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

